#!/usr/bin/env bash
set -euo pipefail

log() { echo "[jupyter-pyscript] $*"; }

SUPERVISOR="http://supervisor"

# ---- sanity checks ----
if [[ -z "${SUPERVISOR_TOKEN:-}" ]]; then
  log "ERROR: SUPERVISOR_TOKEN is not set. Is hassio_api enabled for this add-on?"
  exit 1
fi

# ---- fetch options ----
log "Fetching add-on options from Supervisor..."
OPTIONS_JSON="$(curl -fsS \
  -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
  "${SUPERVISOR}/addons/self/options")"

# Requires jq (recommended). If you don't want jq, we can use python -c as fallback.
need_jq() { command -v jq >/dev/null 2>&1; }
if ! need_jq; then
  log "ERROR: jq not found. Install jq in the image (apk add --no-cache jq OR apt-get install -y jq)."
  exit 1
fi

HA_URL="$(echo "$OPTIONS_JSON" | jq -r '.options.ha_url // empty')"
HA_HOST="$(echo "$OPTIONS_JSON" | jq -r '.options.ha_host // empty')"
HA_TOKEN="$(echo "$OPTIONS_JSON" | jq -r '.options.token // empty')"

if [[ -z "$HA_URL" || -z "$HA_HOST" || -z "$HA_TOKEN" ]]; then
  log "ERROR: Missing required add-on options."
  log "       Need ha_url, ha_host, token (Home Assistant long-lived token)."
  exit 1
fi

# ---- paths ----
PYCONF_DIR="/config/pyscript"
PYCONF_FILE="${PYCONF_DIR}/pyscript.conf"

# ---- create directories (owned by add-on) ----
log "Ensuring ${PYCONF_DIR} exists..."
mkdir -p "${PYCONF_DIR}/apps" "${PYCONF_DIR}/modules"

# Safety: refuse to operate on symlinked dirs (avoid weird edge cases)
if [[ -L "${PYCONF_DIR}" ]]; then
  log "ERROR: ${PYCONF_DIR} is a symlink; refusing to chown for safety."
  exit 1
fi

# ---- fix ownership for only our subtree ----
# Determine jovyan UID/GID dynamically so it works even if image changes.
JOVYAN_UID="$(id -u jovyan)"
JOVYAN_GID="$(id -g jovyan)"

log "Fixing ownership under ${PYCONF_DIR} to jovyan (${JOVYAN_UID}:${JOVYAN_GID})..."
chown -R "${JOVYAN_UID}:${JOVYAN_GID}" "${PYCONF_DIR}"

# Reasonable perms: dirs 775, files 664 (tweak if you prefer)
find "${PYCONF_DIR}" -type d -exec chmod 775 {} \;
find "${PYCONF_DIR}" -type f -exec chmod 664 {} \;

# ---- write pyscript.conf ----
log "Writing ${PYCONF_FILE}..."
umask 002
cat >"${PYCONF_FILE}" <<EOF
# Auto-generated by add-on startup
ha_url = "${HA_URL}"
ha_host = "${HA_HOST}"
token = "${HA_TOKEN}"
EOF
chown "${JOVYAN_UID}:${JOVYAN_GID}" "${PYCONF_FILE}"
chmod 664 "${PYCONF_FILE}"

# ---- drop privileges & start jupyter ----
log "Starting Jupyter as jovyan..."
# If your image has gosu:
if command -v gosu >/dev/null 2>&1; then
  exec gosu jovyan:users jupyter lab --ip=0.0.0.0 --no-browser
fi
# Debian alternative: su
exec su -s /bin/bash -c 'exec jupyter lab --ip=0.0.0.0 --no-browser' jovyan
